In [7]:
import numpy as np
from scipy import sparse
import numpy

In [8]:
X=np.random.uniform(size=(6,6))
print(X)

[[0.02641151 0.94972431 0.60264149 0.90601979 0.73523059 0.54185179]
 [0.94700058 0.9561012  0.34751586 0.28903108 0.94932749 0.63442633]
 [0.67318589 0.56042664 0.41062681 0.09465856 0.14892904 0.6196727 ]
 [0.6976658  0.53321446 0.33430537 0.61631392 0.85165664 0.50745988]
 [0.87054706 0.03445044 0.21158966 0.56514191 0.59363694 0.06273944]
 [0.89102748 0.20155194 0.31270306 0.28126517 0.46029436 0.42238973]]


In [9]:
X[X<0.7]=0  # Create a sparse Matrix
print(X)

[[0.         0.94972431 0.         0.90601979 0.73523059 0.        ]
 [0.94700058 0.9561012  0.         0.         0.94932749 0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.85165664 0.        ]
 [0.87054706 0.         0.         0.         0.         0.        ]
 [0.89102748 0.         0.         0.         0.         0.        ]]


In [10]:
print( numpy.linalg.det( X ) ) # Calculte the deetrminate of X

0.0


In [13]:
import math   # Calculo do dterminate usando cofatores
import numpy as np

def determinant(A):
    n=np.shape(A)[0]
    if(n==2):
        det=A[0,0]*A[1,1]-A[0,1]*A[1,0]
    else:    
        det=0
        for i in range(n):
            # Expansion by first line
            newMatrix=A[1:,:]
            newMatrix=np.delete(newMatrix,i,axis=1)
            det=det+math.pow(-1,1+i+1)*A[0,i]*(determinant(newMatrix))
    return det

if __name__ == '__main__':

    print ("Matrix 1")
    A=((1, 2, 3),(4, 5 , 6),(7,8,9))
    print ("Numpy: ", np.linalg.det(A))
    A=np.array(A)
    print ("Ours: ",determinant(A))

    print ("Matrix 2")
    A=((1, 2, 3),(4, 5 , 6),(7,8,13))
    print ("Numpy: ",np.linalg.det(A))
    A=np.array(A)
    print ("Ours: ",determinant(A))

    print ("Matrix 3")
    A=((2, -2, 0, 3),(-5, 2 , 2, 1),(1,-1,0,-3),(2, 0, 0, -1))
    print ("Numpy: ",np.linalg.det(A))    
    A=np.array(A)
    print ("Ours: ",determinant(A))

Matrix 1
Numpy:  6.66133814775094e-16
Ours:  0.0
Matrix 2
Numpy:  -11.999999999999995
Ours:  -12.0
Matrix 3
Numpy:  -36.000000000000014
Ours:  -36.0


In [15]:
from scipy import linalg  # Cálculo de determinantes
arr = np.array([[1, 2],
                [3, 4]])
linalg.det(arr)

arr = np.array([[3, 2],
                [6, 4]])
linalg.det(arr)
#linalg.det(np.ones((3, 4))) #erro

0.0

In [16]:
arr = np.array([[1, 2],  # Verifica se a matriz é singular
                [3, 4]])
iarr = linalg.inv(arr)
iarr
np.allclose(np.dot(arr, iarr), np.eye(2))

True

In [18]:
arr = np.array([[3, 7],  #Cálculo da inversa de matriz
                [6, 4]])
linalg.inv(arr)

array([[-0.13333333,  0.23333333],
       [ 0.2       , -0.1       ]])

In [20]:
arr = np.arange(9).reshape((3, 3)) + np.diag([1, 0, 1]) #Decomposição em valores singulares
uarr, spec, vharr = linalg.svd(arr)
spec

array([14.88982544,  0.45294236,  0.29654967])

In [21]:
sarr = np.diag(spec)   #Recomposição da matrix
svd_mat = uarr.dot(sarr).dot(vharr)
np.allclose(svd_mat, arr)

True