In [1]:
import numpy as np
k=0.25
l=2.55
pho1=0.580
pho2=0.001
pho3=0.2
pho4=0.3
beta=2.55
betalinha=7.65
gammaa=0.94
gammai=0.27
gammar=0.5
gammap=1
deltah=0.3
deltai=3.5
deltap=1
betal=beta*l
kpho1=k*pho1
kpho3=k*pho3
kpho4=k*pho4
wi=gammaa+gammai+deltai
kpho2=k*pho2
wp=gammaa+gammai+deltap
wh=gammaa+gammai+deltah

In [20]:
Jv= [ [0,beta,betalinha,betal,0], [0,0,0,0, kpho3],[0,0,0,0,kpho4], [0,0,0,0,0], [0,0,0,0,0]]
print("Determinante de Jv é: ", np.linalg.det( Jv ))
autovalores,autovetores = np.linalg.eig(Jv)
print("Autovalores de Jv são: ", autovalores)

Determinante de Jv é:  0.0
Autovalores de Jv são:  [0. 0. 0. 0. 0.]


In [23]:
Jf=[[k,0,0,0,0],[-k*pho1,wi,0,0,0],[-kpho2,0,wp,0,0],[0,gammaa,gammaa,wh,0],[-k*(1-pho1-pho2),0,0,0,k*(pho3+pho4)]]
inversa=np.linalg.inv(Jf)
print("Determinante de Jf é: ", np.linalg.det( Jf ))
print("A inversa de Jf é:", inversa)
print("Determinante de inversa é: ", np.linalg.det( Jf ))

Determinante de Jf é:  0.4911794062500001
A inversa de Jf é: [[ 4.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 1.23142251e-01  2.12314225e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 4.52488688e-04  0.00000000e+00  4.52488688e-01  0.00000000e+00
   0.00000000e+00]
 [-7.69397714e-02 -1.32169120e-01 -2.81681700e-01  6.62251656e-01
   0.00000000e+00]
 [ 3.35200000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   8.00000000e+00]]
Determinante de inversa é:  0.4911794062500001


In [26]:
resultado=Jv*inversa
print(resultado)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [-0. -0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
