In [9]:
def crie_matriz(n_linhas, n_colunas, valor):  # Cria matriz com um valor fixo
    matriz=[]
    for i in range(n_linhas):
        linha=[]
        for j in range(n_colunas):
            linha+= [valor]
            matriz+=[linha]
        return matriz

In [10]:
A = crie_matriz(5,5,2)
A

[[2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2]]

In [11]:
import random  # Somente se for usar uma matriz com elementos aleatórios
def matriz(n_linhas, n_colunas):
    matriz = [] # Matriz
    linha = [] # Linha

    while len(matriz) != n_linhas: # Quando o número de elementos da matriz(linhas) forem diferentes da quantidade máxima definida pelo usuário, ele ficará rodando.
        #n = random.randint(0,99) # Utilizei random para adicionar os valores
        n =float(input('digite o valor do elemento'))
        linha.append(n) # Adiciono n à linha

        if len(linha) == n_colunas: # Se a quantidade de elementos for igual à quantidade de colunas definida pelo usuário :
            matriz.append(linha) # Adiciono a linha à matriz
            linha = [] # E zero a "linha" para adicionar outra à matriz
    return matriz # Retorno a mesma


A=matriz(3,3)
print(A)

digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
digite o valor do elemento0
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]


In [12]:
def somar(m1, m2):
    matriz_soma = []
    # Supondo que as duas matrizes possuem o mesmo tamanho
    quant_linhas = len(m1) # Conta quantas linhas existem
    quant_colunas = len(m1[0]) # Conta quantos elementos têm em uma linha
    for i in range(quant_linhas):
        # Cria uma nova linha na matriz_soma
        matriz_soma.append([])
        for j in range(quant_colunas):
            # Somando os elementos que possuem o mesmo índice
            soma = m1[i][j] + m2[i][j]
            matriz_soma[i].append(soma)
    return matriz_soma

In [13]:
S=somar(A,A)
print(S)

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]


In [14]:
def mult_escalar(matriz, escalar):
    matriz_mult = []
    quant_linhas = len(matriz) # Conta quantas linhas existem
    quant_colunas = len(matriz[0]) # Conta quantos elementos têm em uma linha
    for i in range(quant_linhas):
        # Cria uma nova linha na matriz_mult
        matriz_mult.append([])
        for j in range(quant_colunas):
            # Multiplicando cada elemento pelo escalar
            mult = escalar * matriz[i][j]
            matriz_mult[i].append(mult)
    return matriz_mult

In [15]:
M=mult_escalar(A,3)
print(M)

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]


In [16]:
def subtrair(m1, m2):
    matriz_subtrair = []
    # Supondo que as duas matrizes possuem o mesmo tamanho
    quant_linhas = len(m1) # Conta quantas linhas existem
    quant_colunas = len(m1[0]) # Conta quantos elementos têm em uma linha
    for i in range(quant_linhas):
        # Cria uma nova linha na matriz_soma
        matriz_subtrair.append([])
        for j in range(quant_colunas):
            # Somando os elementos que possuem o mesmo índice
            subtrair = m1[i][j] - m2[i][j]
            matriz_subtrair[i].append(subtrair)
    return matriz_subtrair

In [17]:
S=subtrair(A,A)
print(S)

[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]


In [18]:
import numpy as np
Determinante =np.linalg.det(A)
print(Determinante)

0.0


In [19]:
autovalores,autovetores = np.linalg.eig(A)
print(autovalores,autovetores)

[0. 0. 0.] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
import numpy as np 
A = np.array(((1, 3, 2), (3, 4 ,0), (1, 2, 3)))
print("Matriz A \n",A)
b = np.array((1, -2, 4))
print("Vetor b \n",b)
c  =np.linalg.solve(A, b)
print("Solução de Ax=b é c = ",c)
Determinante =np.linalg.det(A)
print(Determinante)

Matriz A 
 [[1 3 2]
 [3 4 0]
 [1 2 3]]
Vetor b 
 [ 1 -2  4]
Solução de Ax=b é c =  [ 0.90909091 -1.18181818  1.81818182]
-11.000000000000002


In [21]:
import numpy as np
A = np.array([[1, 3, 2], [3, 4, 0]])
B = np.array([[3, -1], [2, 1], [5, 2]])
C = np.matmul(A, B)
print("Matriz A: \n", A)
print("Matriz B: \n", B)
print("Matriz AxB: \n", C)


Matriz A: 
 [[1 3 2]
 [3 4 0]]
Matriz B: 
 [[ 3 -1]
 [ 2  1]
 [ 5  2]]
Matriz AxB: 
 [[19  6]
 [17  1]]


In [22]:
class Matriz: # Código paar multiplicação de matrizes usando Classes
    def __init__(self, mat):
        self.mat = mat
        self.lin = len(mat)
        self.col = len(mat[0])

    def getLinha(self, n):
        return [i for i in self.mat[n]]

    def getColuna(self, n):
        return [i[n] for i in self.mat]

    # opcional: dar overload no operador de multiplicação
    def __mul__(self, mat2):
        matRes = []

        for i in range(self.lin):           
            matRes.append([])

            for j in range(mat2.col):
                listMult = [x*y for x, y in zip(self.getLinha(i), mat2.getColuna(j))]
                matRes[i].append(sum(listMult))

        return matRes

In [23]:
mat1 = Matriz([[2, 3], [4, 6]])
mat2 = Matriz([[1, 3, 0], [2, 1, 1]])
print(mat1*mat2)

[[8, 9, 3], [16, 18, 6]]


In [24]:
def getLinha(matriz, n):
    return [i for i in matriz[n]]  # ou simplesmente return matriz[n]

def getColuna(matriz, n):
    return [i[n] for i in matriz]

mat1 = [[2, 3], [4, 6]]            # uma matriz 2x2
mat1lin = len(mat1)                # retorna 2
mat1col = len(mat1[0])             # retorna 2

mat2 = [[1, 3, 0], [2, 1, 1]]      # uma matriz 2x3
mat2lin = len(mat2)                # retorna 2
mat2col = len(mat1[0])             # retorna 3

matRes = []                        # deverá ser uma matriz 2x3
for i in range(mat1lin):           
    matRes.append([])

    for j in range(mat2col):
        # multiplica cada linha de mat1 por cada coluna de mat2;
        listMult = [x*y for x, y in zip(getLinha(mat1, i), getColuna(mat2, j))]

        # e em seguida adiciona a matRes a soma das multiplicações
        matRes[i].append(sum(listMult))

print(matRes)

[[8, 9], [16, 18]]


In [27]:
import numpy as np
k=0.25
l=2.55
pho1=0.580
pho2=0.001
pho3=0.2
pho4=0.3
beta=2.55
betalinha=7.65
gammaa=0.94
gammai=0.27
gammar=0.5
gammap=1
deltah=0.3
deltai=3.5
deltap=1
betal=beta*l
kpho1=k*pho1
kpho3=k*pho3
kpho4=k*pho4
wi=gammaa+gammai+deltai
kpho2=k*pho2
wp=gammaa+gammai+deltap
wh=gammaa+gammai+deltah

R = [ [0, 0, -beta, -betalinha, -betal,0,0,0], [0, -k ,beta, betalinha, betal,0,0,0], [0, kpho1, -wi,0,0,kpho3,0,0], [0,kpho2,0,-wp,0,kpho4,0,0], [0,k*(1-pho1-pho2),0,0,0,k*(pho3+pho4),0,0], [0,0,0,gammai,gammar,0,0,0], [0,0,deltai,deltap,deltah,0,0,0], [0,0,deltai,deltap,deltah,0,0,0]]
print(np.linalg.det( R ))
#Determinante =np.linalg.det(R)
autovalores,autovetores = np.linalg.eig(R)
print(autovalores)

0.0
[ 0.          0.          0.         -4.79409338 -2.22369592 -0.91892752
  0.7928024  -0.02608558]


In [28]:
import numpy

matriz = [ [1, 1, 1], [2, 2, 2], [3, 3, 3] ]
print(matriz)

print( numpy.linalg.det( matriz ) )

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
0.0


In [6]:
import numpy
R1= [ [-k,beta,betalinha,-betal], [kpho1,-wi,0,0], [kpho2,0,-wp,0], [0,gammaa,gammaa,-wh]]
print( numpy.linalg.det( R1 ) )
autovalores,autovetores = np.linalg.eig(R1)
print(autovalores)

4.647840483375
[-4.84817976 -0.33808614 -1.28216993 -2.21156417]


In [7]:
inversa=numpy.linalg.inv(R1)
print(inversa)

[[-3.38172987e+00  1.07548624e+00 -5.51189237e+00  1.45627142e+01]
 [-1.04108457e-01 -1.79204776e-01 -1.69686708e-01  4.48321351e-01]
 [-3.82548628e-04  1.21661340e-04 -4.53112205e-01  1.64736586e-03]
 [-6.50473808e-02 -1.11482204e-01 -3.87702634e-01 -3.82138680e-01]]


In [8]:
import numpy
Ri= [ [k,0,0,0], [-kpho1,wi,0,0], [-kpho2,0,wp,0], [0,-gammaa,-gammaa,wh]]
print( numpy.linalg.det( Ri ) )
autovalores,autovetores = np.linalg.eig(Ri)
print(autovalores)

3.9294352500000005
[1.51 4.71 2.21 0.25]


In [9]:
inversa=numpy.linalg.inv(Ri)
print(inversa)

[[4.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.23142251e-01 2.12314225e-01 0.00000000e+00 0.00000000e+00]
 [4.52488688e-04 0.00000000e+00 4.52488688e-01 0.00000000e+00]
 [7.69397714e-02 1.32169120e-01 2.81681700e-01 6.62251656e-01]]


In [23]:
Ri= Matriz([ [k,0,0,0], [-kpho1,wi,0,0], [-kpho2,0,wp,0], [0,-gammaa,-gammaa,wh]])
Jf= Matriz([ [0,beta,betalinha,betal], [0,0,0,0], [0,0,0,0], [0,0,0,0]])
temporaria =Matriz(inversa)

print(Jf*temporaria)
Jf1=[ [0,beta,betalinha,betal], [0,0,0,0], [0,0,0,0], [0,0,0,0]]
print(Jf1)

[[0.8177751410651186, 1.400830978192095, 5.293173713703515, 4.306291390728477], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0]]
[[0, 2.55, 7.65, 6.5024999999999995], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [14]:
raio=Jf*temporaria
autovalores,autovetores = np.linalg.eig(raio)
print(autovalores)

[0.81777514 0.         0.         0.        ]


In [26]:
M=[ [k,0,0,0], [-kpho1,wi,0,0], [-kpho2,0,wp,0], [0,-gammaa,-gammaa,wh]]
inversa1=numpy.linalg.inv(M)
print(inversa1)
novamatriz=M*inversa1
print(novamatriz)

[[4.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.23142251e-01 2.12314225e-01 0.00000000e+00 0.00000000e+00]
 [4.52488688e-04 0.00000000e+00 4.52488688e-01 0.00000000e+00]
 [7.69397714e-02 1.32169120e-01 2.81681700e-01 6.62251656e-01]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.78556263e-02  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.13122172e-07  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.24238973e-01 -2.64780798e-01  1.00000000e+00]]
