# Método mais simples:Matrizes de tamanho fixo

In [9]:
import numpy as np
from numpy import*

In [29]:
A=np.array([[1.,2.,1.],[3.,-2.,-2.],[1.,3.,-1.]])

In [30]:
B=np.array([1.,-1.,-9.])

In [31]:
n =np.size(B)

In [32]:
for k in range(n-1):
    for i in range(k+1,n):
        m = A[i,k]/A[k,k]
        A[i,:] = A[i,:] - m*A[k,:]
        B[i] = B[i] - m*B[k]
        print(A,B)
        print("")
        

[[ 1.  2.  1.]
 [ 0. -8. -5.]
 [ 1.  3. -1.]] [ 1. -4. -9.]

[[ 1.  2.  1.]
 [ 0. -8. -5.]
 [ 0.  1. -2.]] [  1.  -4. -10.]

[[ 1.     2.     1.   ]
 [ 0.    -8.    -5.   ]
 [ 0.     0.    -2.625]] [  1.   -4.  -10.5]



In [33]:
print(linalg.solve(A,B))

[ 1. -2.  4.]


# Método mais completo:Matrizes de tamanho qualquer

In [1]:
import numpy as np
from numpy import*

In [2]:
print("Resolução de sistemas pelo método da eliminação gaussiana")
print("Digite a quantidade linhas deste sistema")

Resolução de sistemas pelo método da eliminação gaussiana
Digite a quantidade linhas deste sistema


In [3]:
L=int(input("Digite o número de linhas:  "))
C=L #Matriz quadrada

Digite o número de linhas:  3


In [4]:
print("Digite a matriz de termos dependentes")
M=[[0]*C for i in range(L)]
for i in range(L):
    for j in range(C):
        M[i][j] = float(input('Elemento ['+str(i+1)+']'+'['+str(j+1)+']: '))
f =np.array(matrix(M))
print(f)

Elemento [1][1]: 1
Elemento [1][2]: 2
Elemento [1][3]: 1
Elemento [2][1]: 3
Elemento [2][2]: -2
Elemento [2][3]: -2
Elemento [3][1]: 1
Elemento [3][2]: 3
Elemento [3][3]: -1
[[ 1.  2.  1.]
 [ 3. -2. -2.]
 [ 1.  3. -1.]]


In [5]:
print("Digite a matriz de termos independentes")
C1=1
M1=[[0]*C1 for i in range(L)]
for i in range(L):
    for j in range(C1):
        M1[i][j] = float(input('Elemento ['+str(i+1)+']'+'['+str(j+1)+']: '))
f1=np.array(matrix(M1))
print(f1)

Digite a matriz de termos independentes
Elemento [1][1]: 1
Elemento [2][1]: -1
Elemento [3][1]: -9
[[ 1.]
 [-1.]
 [-9.]]


In [6]:
# Impressão do Sistema linear
M2=[[0]*C1 for i in range(L)]
for i in range(L):
    for j in range(C1):
        M2[i][j] = 'x'+ str(i+1)
f2=np.array(matrix(M2))
print('MATRIZ INICIAL:' '\n''MATRIZ A \t\t\t MATRIZ B''\n'+'\n'.join('{}\t{}={}'.format(f,f2,f1) for f,f2,f1 in zip(f,f2,f1)))

MATRIZ INICIAL:
MATRIZ A 			 MATRIZ B
[1. 2. 1.]	['x1']=[1.]
[ 3. -2. -2.]	['x2']=[-1.]
[ 1.  3. -1.]	['x3']=[-9.]


In [7]:
print("Resolvendo o sistema via Gauss")

Resolvendo o sistema via Gauss


In [8]:
#Método da eliminação Gaussiana
for k in range(L-1):
    for i in range(k+1,L):
        m=(f[i,k]/f[k,k])
        f[i,:]=f[i,:]-m*f[k,:]
        f1[i,:]=f1[i,:]-m*f1[k,:]
        print('Pivô= ', f[k,k])
        print('m=',m)
        print('\n'.join('{}\t{}={}'.format(f,f2,f1) for f,f2,f1 in zip(f,f2,f1)))
        print('') 
        

Pivô=  1.0
m= 3.0
[1. 2. 1.]	['x1']=[1.]
[ 0. -8. -5.]	['x2']=[-4.]
[ 1.  3. -1.]	['x3']=[-9.]

Pivô=  1.0
m= 1.0
[1. 2. 1.]	['x1']=[1.]
[ 0. -8. -5.]	['x2']=[-4.]
[ 0.  1. -2.]	['x3']=[-10.]

Pivô=  -8.0
m= -0.125
[1. 2. 1.]	['x1']=[1.]
[ 0. -8. -5.]	['x2']=[-4.]
[ 0.     0.    -2.625]	['x3']=[-10.5]



In [10]:
print("A solução do sistema é:  ")
x=zeros(L)
x[L-1]=f1[L-1]/f[L-1,L-1]
print('x'+str(L)+'=',x[L-1])
for i in range(L-2,-1,-1):
    sum_ax=0
    for j in range(i+1,L):
        sum_ax += f[i,j]*x[j]
    x[i]=(f1[i]-sum_ax)/f[i,i]
    print('x' + str(i+1)+'=',x[i])

A solução do sistema é:  
x3= 4.0
x2= -2.0
x1= 1.0
