# Solução do sistema linear 

In [26]:
import numpy as np  # Ax=b, então x=inv(A).b

A = np.array(((2,2),(1,1.01)))
print("Matriz A:", A)

print("____________________________________________________________________________________________________")
b = np.array((8,4.01))
print("Vetor b \n:  ",b)


print("____________________________________________________________________________________________________")
x  = np.linalg.solve(A, b)
print("Solução de Ax=b é x \n:   = ",x)


print("____________________________________________________________________________________________________")

Inversa = np.linalg.inv(A)
print("A inversa de A é \n: ", Inversa)

print("____________________________________________________________________________________________________")

Determinante = np.linalg.det(A)   
print("O determinante de A é \n: ", Determinante)

print("____________________________________________________________________________________________________")
M = np.matmul(Inversa,b)
print(M)



#numero_condicionamento = np.linalg.cond(A)
#print(numero_condicionamento)

#Determinante = np.linalg.det(A)    # Se o determinante não é nulo, então os vetores são LI(Linearmente Indpendentes)
#print("O determinante de A é: ", Determinante)


#norma = np.linalg.norm(A)
#print(norma)

#rank = np.linalg.matrix_rank(A)
#print(rank)

Matriz A: [[2.   2.  ]
 [1.   1.01]]
____________________________________________________________________________________________________
Vetor b 
:   [8.   4.01]
____________________________________________________________________________________________________
Solução de Ax=b é x 
:   =  [3. 1.]
____________________________________________________________________________________________________
A inversa de A é 
:  [[  50.5 -100. ]
 [ -50.   100. ]]
____________________________________________________________________________________________________
O determinante de A é 
:  0.02000000000000001
____________________________________________________________________________________________________
[3. 1.]


# Determinate da matiz principal

In [19]:
Determinante = np.linalg.det(A)    # Se o determinante não é nulo, então os vetores são LI(Linearmente Indpendentes)
print("O determinante de A é: ", Determinante)

Inversa = np.linalg.inv(A)
print("A inversa de A é: ", Inversa)

norma_inv = np.linalg.norm(Inversa)
print(norma_inv)

#n_cond = (norma_inv)*(norma)
#print(n_cond)

O determinante de A é:  -4.0
A inversa de A é:  [[ 0.25  0.5 ]
 [ 0.25 -0.5 ]]
0.7905694150420949


# Regra de Cramer

In [2]:
import numpy as np
D = np.array(((1, 3),(5,-7)))
Dx = np.array(((8,3),(11,-7)))
Dy = np.array(((1,8),(5,11)))
Determinante = np.linalg.det(D)
Determinantex = np.linalg.det(Dx)
Determinantey = np.linalg.det(Dy)
x=Determinantex/Determinante
y=Determinantey/Determinante

print("O valor de x é: ", round(x,2))
print("O valor de y é: ", round(y,2))

O valor de x é:  4.05
O valor de y é:  1.32


# Autovalores e Autovetores

In [18]:
autovalores,autovetores = np.linalg.eig(A)
print(autovalores,autovetores)

[ 2.56155281 -1.56155281] [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


# Raio espectral com três autovalores

In [5]:
primeiro = float(input('Primeiro numero: '))
segundo  = float(input('Segundo numero : '))
terceiro = float(input('Terceiro numero: '))

# Achando o maior número
maior = abs(primeiro)

if (segundo > maior):
    maior = abs(segundo)
if (terceiro > maior):
    maior = abs(terceiro)

print('Maior Valor em Módulo, portanto é o raio espectral: ',maior)

# Achando o menor número
menor = abs(primeiro)

if (segundo < menor):
    menor = abs(segundo)
if (terceiro < menor):
    menor = abs(terceiro)

print('Menor Valor em Módulo, não serve como raio espectral: ',menor)

Primeiro numero: 0.86
Segundo numero : -0.37
Terceiro numero: -0.33
Maior Valor em Módulo, portanto é o raio espectral:  0.86
Menor Valor em Módulo, não serve como raio espectral:  0.33


# Estabilidade do sistema

In [6]:
import numpy as np 
Ae = np.array(((2.01, 1.01, -3.01), (1, 1 ,1), (3, -3, 9))) # Alterando a primeira linha da matriz
print("Matriz A \n",Ae)
be = np.array((1, 0, -3))
print("Vetor b \n",b)
ce  =np.linalg.solve(Ae, be)
print("Solução de Ax=b é c = ",ce)

Matriz A 
 [[ 2.01  1.01 -3.01]
 [ 1.    1.    1.  ]
 [ 3.   -3.    9.  ]]
Vetor b 
 [ 1  0 -3]
Solução de Ax=b é c =  [-0.00166113  0.25083056 -0.24916944]


In [7]:
Determinantenovo =np.linalg.det(Ae)
print("O determinante da matriz A modificada é: ", Determinantenovo)

O determinante da matriz A modificada é:  36.11999999999999


# Decomposição LU em Python

In [3]:
import  numpy as np   # A.x =b   (L.U)x=b
A = np.array(((2, 3, 1,5,7,8), (1, 2 ,3,-3,4,-1), (3, 1, 2,1,-2,5),(4,3,1,-1,9,8),(5,11,-1,2,3,7),(10,12,8,9,-3,5)))
b = np.array((7, 3, -2,4,5,9))

In [4]:
import time
inicio = time.time()
def LU(A,b):   #Ax=b, LUx=b, Ly=b, Ux=y, x=Linv.Uinv.b : solução
    import scipy.linalg
    L,U =scipy.linalg.lu(A,permute_l=True)
    y=scipy.linalg.solve(L,b)
    x=scipy.linalg.solve(U,y)
    return x
print("A solução do sistema linear é: ", LU(A,b))
fim = time.time()

print("O tempo de execução para encontrar a solução do sistema é: ",(fim - inicio)*1000)


A solução do sistema linear é:  [-0.13167204  0.46327238  0.32489542  0.70160153  0.73647663 -0.38933907]
O tempo de execução para encontrar a solução do sistema é:  298.1891632080078


In [5]:
import numpy as np  # Ax=b, então x=inv(A).b
import time
A1 = np.array(((2, 3, 1,5,7,8), (1, 2 ,3,-3,4,-1), (3, 1, 2,1,-2,5),(4,3,1,-1,9,8),(5,11,-1,2,3,7),(10,12,8,9,-3,5)))
b1 = np.array((7, 3, -2,4,5,9))


inicio = time.time()
Inversa = np.linalg.inv(A1)
x  = np.dot(Inversa, b1)
print("Solução de Ax=b é x \n:   = ",x)
fim = time.time()

print("O tempo de execução para encontrar a solução do sistema é: ",(fim - inicio)*1000)



Solução de Ax=b é x 
:   =  [-0.13167204  0.46327238  0.32489542  0.70160153  0.73647663 -0.38933907]
O tempo de execução para encontrar a solução do sistema é:  12.96544075012207


In [20]:
from scipy.linalg import lu
A = np.array(((2, 3, 1), (1, 2 ,3), (3, 1, 2)))
p, l, u = lu(A)
print(lu(A))

(array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]]), array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.71428571, 1.        ]]), array([[ 3.        ,  1.        ,  2.        ],
       [ 0.        ,  2.33333333, -0.33333333],
       [ 0.        ,  0.        ,  2.57142857]]))


In [54]:
import numpy as np                     # Exercício sobre solução de sistemas lineares usando a inversa da matriz
import scipy.linalg
import  numpy as np   # Ax=b, então x=Inv(A)*b
A = np.array(((3, -4, 1), (1, 2 ,2), (4, 0, -3)))
b = np.array((9, 3, -2))
A_inv =np.linalg.inv(A)
#print(A_inv)
x=(A_inv@b)
print(x)

[ 1. -1.  2.]


# Vetores em Python

In [6]:
import numpy as np

In [11]:
vetor1 = np.array([67])
vetor2 = np.array([67, 250])
vetor3 = np.array([67, 250, 2])
vetor4 = np.array([-50, 20, 27])

In [8]:
print(vetor1,vetor2,vetor3)

[67] [ 67 250] [ 67 250   2]


In [15]:
print(2*vetor3 - 4*vetor4)

[ 334  420 -104]


In [19]:
#Métodos úteis da np.array
meu_vetor = np.array([10, -32, 39, 42, 33, 70, 89, 105])
print("A média dos elementos do meu vetor é: ", meu_vetor.sum()/len(meu_vetor)) 
print("O elemento mínimo do meu vetor é: ", meu_vetor.min())
print("O elemento máximo do meu vetor é: ", meu_vetor.max()) 

A média dos elementos do meu vetor é:  44.5
O elemento mínimo do meu vetor é:  -32
O elemento máximo do meu vetor é:  105


In [20]:
#Soma de vetores
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
soma = x + y 

In [21]:
print(soma)

[ 6  8 10 12]


In [22]:
#Soma escalar
notas = np.array([6.5, 8.0, 7.5, 4.5, 9.0, 6.5, 6.0, 5.5, 7.0, 8.0, 6.5, 7.5])
soma = notas + 0.5  
print(soma)

[7.  8.5 8.  5.  9.5 7.  6.5 6.  7.5 8.5 7.  8. ]


In [23]:
#Multiplicação de vetores
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
mult = x * y  #[5, 12, 21, 32]
print(mult)

[ 5 12 21 32]


In [39]:
#Aplicação: Se temos um vetor com as notas de um aluno.
notas = np.array([10.0, 7.0, 5.5, 6.5, 8.0])

#E temos um vetor com o peso que representa cada uma das notas na disciplina:
pesos = np.array([0.2, 0.1, 0.1, 0.3, 0.3])

#Se multiplicarmos os dois vetores e somar seus valores, temos como resultado a nota que este aluno teve na disciplina:
notaFinal = sum(notas * pesos)

media_ponderada = (notaFinal)/(pesos.sum())

print(media_ponderada)

if 4.0 < media_ponderada < 7.0:
    print("O seu aluno está de recuperação", media_ponderada)
elif (0.0<= media_ponderada<=4.0):
    print("O aluno está reprovado direto!")
else:
    print("O aluno está aprovado", media_ponderada)

7.6
O aluno está aprovado 7.6


In [40]:
#Multiplicação de escalar
valores = np.array([18.0, 16.5, 17.0, 19.5, 18.5])
#E queremos atribuir um peso de 10% para cada um dos valores:
pesos = valores * 0.1  
print(pesos)

[1.8  1.65 1.7  1.95 1.85]


In [41]:
#Produto escalar de vetores
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
prod = np.dot(x, y)
print(prod)

70


In [43]:
x = np.array([1, 2, 3, 4])
prod_quadrado = np.dot(x, x)
print(prod_quadrado)
print(np.sqrt(prod_quadrado))

30
5.477225575051661


In [44]:
#Distância entre pontos
qv = np.array([1,4])    
qa = np.array([2,1])    
tv = np.array([4,2]) 
distancia1 = np.sqrt(sum((qv - tv) ** 2))
distancia2 = np.sqrt(sum((qa - tv) ** 2)) 
print(distancia1)
print(distancia2)

3.605551275463989
2.23606797749979


In [6]:
#Matrizes
A = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8]])

In [7]:
print(A)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#Soma de matrizes
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])

SOMA = A + B
print(SOMA)

[[ 2  4  6  8]
 [10 12 14 16]]


In [9]:
#Transposta da matriz
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
print(A.T)   

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [10]:
#Multiplicação de matrizes
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2],
               [3, 4], 
               [5, 6],
               [7, 8]])
mult = A * B
print(mult)

[[ 50  60]
 [114 140]]


# Avançando na programação

In [31]:
#DEFININDO UM VETOR DE FORMA MAIS AVANÇADA
n = 10;

# Definir vetor/lista com: (10,11,12,13,...10+n-1)
vet = []; # define um vetor vazio
for i in range(0, n, 1) : # ou mais simples neste caso "for i in range(n)"
    vet.append(10+i); # anexe mais um elemento `a lista
# Imprime o vetor/lista de uma so' vez (na mesma linha)
print("\nO vetor: ", end=""); # informe o que vira impresso a seguir (na mesma linha devido ao parametro end=""
print(vet);


O vetor: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
#Defininido uma cadeia de caracteres ("string")
# Definir "string"
string = "0123456789abcdefghih"; 

# Imprimir cada caractere da string com seu codigo ASCII
print("\nImprime caracteres e seus codigos ASCII na forma de tabela\nColuna 1 => caractere; coluna 2 => seu codigo ASCII");
for char in string : # iterador
    print("%20c : %3d" % (char, ord(char))); # funcao ord(.) devolve codigo ASCII do caractere parametro
print(); # quebre a linha

# Agora um entrada de dados via teclado e pegando uma frase como "string" (o ENTER finaliza a frase)
print("Digite uma frase e tecle ENTER/CR");
string = input(); # se usar Python 2 precisa trocar 'input' por 'raw_input'
print("Foi digitada uma frase com %d caracteres: %s" % (len(string), string));

# Observacao: se definiu um vetor como "string" como em (1) acima, NAO e' possivel alterar a "string", por exemplo,
# o comando abaixo resulta erro "TypeError: 'str' object does not support item assignment"
# string[2] = '*'; # isso resultaria erro! experimente


Imprime caracteres e seus codigos ASCII na forma de tabela
Coluna 1 => caractere; coluna 2 => seu codigo ASCII
                   0 :  48
                   1 :  49
                   2 :  50
                   3 :  51
                   4 :  52
                   5 :  53
                   6 :  54
                   7 :  55
                   8 :  56
                   9 :  57
                   a :  97
                   b :  98
                   c :  99
                   d : 100
                   e : 101
                   f : 102
                   g : 103
                   h : 104
                   i : 105
                   h : 104

Digite uma frase e tecle ENTER/CR


In [10]:
#Construindo matriz como vetor de vetor e ilustrando que cada linha dela é um vetor.
# Vetor de vetor ou matriz
# Funcao para somar elementos de um vetor e devolver essa soma
def somalinha (vet):
    tam = len(vet);
    soma = 0;
    for i in range(tam) : 
        soma += vet[i]
    return soma

In [11]:
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
somalinha(A)

matrix([[ 6,  8, 10, 12]])

In [14]:
# Definir vetor/lista com: (0,1,2,3,...n-1)
nl = 3; nc = 4; #Quantidade linhas e colunas
mat = []; # define um vetor vazio
for i in range(0, nl, 1) : # ou mais simples neste caso "for i in range(n)"
    linha = []; # define um vetor vazio
    for j in range(0, nc, 1) : # ou mais simples neste caso "for i in range(n)"
        linha.append(i*nc+j);
    mat.append(linha); # anexe nova linha `a matriz 'mat'
# Imprime o vetor/lista de uma so' vez (na mesma linha)
print("\nA matriz: ", end=""); # informe o que vira impresso a seguir (na mesma linha devido ao parametro end=""
print(mat);


A matriz: [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [15]:
# Pegando o primeiro e segundo elemento da terceira linha de mat: mat[2][1]
prim = mat[2][0]; seg = mat[2][1]; # pegar primeiro e segundo elemento da linha mat[2]
print("O primeiro e segundo elemento da terceira linha da matriz: %d e %d" % (prim, seg));

print("Linhas da matriz: 0=%s ; 1=%s ; 2=%s" % (mat[0], mat[1], mat[2])); # cada linha e' um vetor!
# print(mat[0]); print(mat[1]); print(mat[2]);

O primeiro e segundo elemento da terceira linha da matriz: 8 e 9
Linhas da matriz: 0=[0, 1, 2, 3] ; 1=[4, 5, 6, 7] ; 2=[8, 9, 10, 11]


In [16]:
# Verifique que cada linha da matriz e' de fato um vetor
for i in range(0, nl) :
    print("Soma da linha %2d = %3d" % (i, somalinha(mat[i])));

Soma da linha  0 =   6
Soma da linha  1 =  22
Soma da linha  2 =  38
