In [2]:
from functools import reduce
import numpy as np

x = np.array([2, 4, 6, 8, 10])
y = np.array([0.1825, 0.2019, 0.2621, 0.3721, 0.5123])

def sum_w_exp(arr, exp):
 return reduce(lambda sum, value: sum + value**exp, arr, 0)

n = len(x)
x_sum = sum_w_exp(x, 1)
x2_sum = sum_w_exp(x, 2)
x3_sum = sum_w_exp(x, 3)
x4_sum = sum_w_exp(x, 4)

a = np.array([
 [n, x_sum, x2_sum],
 [x_sum, x2_sum, x3_sum],
 [x2_sum, x3_sum, x4_sum]
])

print("A:")
print(a, end = "\n\n")

def mult_sum_of(x, y, *, x_exp, y_exp):
 sum = 0
 for e1, e2 in zip(x, y):
   sum += e1**x_exp * e2**y_exp
 return sum

y_sum = sum(y)
x_times_y_sum = mult_sum_of(x, y, x_exp = 1, y_exp = 1)
x2_times_y_sum = mult_sum_of(x, y, x_exp = 2, y_exp = 1)

b = np.array([y_sum, x_times_y_sum, x2_times_y_sum])

print("B:")
print(b, end = "\n\n")

"""**SOLUÇÃO UTILIZANDO A BIBLIOTECA linalg.solve DO numpy**"""

result = np.linalg.solve(a, b)
print("Solucao com linalg.solve: ")
print(result, end = "\n\n")

"""**SOLUÇÃO UTILIZANDO A REGRA DE CRAMER**"""

D = np.linalg.det(a)

def cramers_rule(a, b):
 solution = []

 cols = a.shape[1]
 print("Iteracoes:\n")
 for col in range(cols):
   aux = np.copy(a).astype(float)
   aux[:, col] = b
   print(aux)
   det = np.linalg.det(aux)
   print("D" + str(col) + " = " + str(det) + "\n")
   solution.append(det/D)
 return solution

print("--- REGRA DE CRAMER ---\n")
np.set_printoptions(suppress=True)
print("D = " + str(D) + "\n")
result = cramers_rule(a, b)
print("Solucao com a regra de Cramer: ")
print(result)



A:
[[    5    30   220]
 [   30   220  1800]
 [  220  1800 15664]]

B:
[ 1.5309 10.845  88.4404]

Solucao com linalg.solve: 
[ 0.20294    -0.02095286  0.00520357]

--- REGRA DE CRAMER ---

D = 44800.00000000021

Iteracoes:

[[    1.5309    30.       220.    ]
 [   10.845    220.      1800.    ]
 [   88.4404  1800.     15664.    ]]
D0 = 9091.712000000038

[[    5.         1.5309   220.    ]
 [   30.        10.845   1800.    ]
 [  220.        88.4404 15664.    ]]
D1 = -938.6880000000031

[[   5.       30.        1.5309]
 [  30.      220.       10.845 ]
 [ 220.     1800.       88.4404]]
D2 = 233.1200000000012

Solucao com a regra de Cramer: 
[0.2029399999999999, -0.020952857142857113, 0.005203571428571431]
